
package Interfaz;


import static Interfaz.MiniAbastos.produc;
import static Interfaz.MiniAbastos.carrito;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class venta_empresa extends javax.swing.JPanel {

    
    public venta_empresa() {
        MiniAbastos.deserializarObjetos();
        initComponents();
         
        addRowToJTable();
        
        for(int i = 0;i<produc.size();i++){
        jComboBox1.addItem(produc.get(i).Nombre);
        }
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Text2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Venta Empresa");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("ID");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setText("Ingresa el ID");
        ID.setBorder(null);
        ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDMousePressed(evt);
            }
        });
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 360, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 360, 10));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Nombre");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        Nombre.setForeground(new java.awt.Color(204, 204, 204));
        Nombre.setText("Ingresa el nombre");
        Nombre.setBorder(null);
        Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreMousePressed(evt);
            }
        });
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 360, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 360, 10));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Ubicación");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        Tipo.setForeground(new java.awt.Color(204, 204, 204));
        Tipo.setText("Ingresa el tipo");
        Tipo.setBorder(null);
        Tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TipoMousePressed(evt);
            }
        });
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 360, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 360, 10));

        jPanel1.setBackground(new java.awt.Color(47, 45, 46));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar Cliente");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, -1));

        jPanel2.setBackground(new java.awt.Color(47, 45, 46));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar a carrito");
        jPanel2.add(jLabel2);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 100, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(402, 402));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 310, 270));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producto" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 140, -1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jPanel4.setBackground(new java.awt.Color(41, 112, 202));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("$ 0.00 ");
        jPanel4.add(jLabel4);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 70, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setText("EL TOTAL ES :   ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void IDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMousePressed

           if (ID.getText().equals("Ingresa el ID")) {
            ID.setText("");
            ID.setForeground(Color.black);}
            
            if (Nombre.getText().isEmpty()) {
            Nombre.setText("Ingresa el nombre");
            Nombre.setForeground(Color.gray);
        }
               if (Tipo.getText().isEmpty()) {
            Tipo.setText("Ingresa el tipo");
            Tipo.setForeground(Color.gray);
        }
              
 
    }//GEN-LAST:event_IDMousePressed

    private void NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreMousePressed
        if (ID.getText().isEmpty()) {
            ID.setText("Ingresa el ID");
            ID.setForeground(Color.gray);}
            
            if (Nombre.getText().equals("Ingresa el nombre")) {
            Nombre.setText("");
            Nombre.setForeground(Color.black);
        }
               if (Tipo.getText().isEmpty()) {
            Tipo.setText("Ingresa el tipo");
            Tipo.setForeground(Color.gray);
        }
           
    }//GEN-LAST:event_NombreMousePressed

    private void TipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoMousePressed
          if (ID.getText().isEmpty()) {
            ID.setText("Ingresa el ID");
            ID.setForeground(Color.gray);}
            
            if (Nombre.getText().isEmpty()) {
            Nombre.setText("Ingresa el nombre");
            Nombre.setForeground(Color.gray);
        }
               if (Tipo.getText().equals("Ingresa el tipo")) {
            Tipo.setText("");
            Tipo.setForeground(Color.black);
        }
                 
    }//GEN-LAST:event_TipoMousePressed

    public void addRowToJTable(){
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
Object rowData[] = new Object [5];
for(int i = 0;i<carrito.size();i++){
rowData[0]=carrito.get(i).ID;
rowData[1]=carrito.get(i).Nombre;
rowData[2]=carrito.get(i).Tipo;
rowData[3]=carrito.get(i).Precio;
rowData[4]=carrito.get(i).Cantidad;
model.addRow(rowData);
} 

 


}
 public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        //cargaTicket();
    }
    
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        int id = Integer.decode(ID.getText());
        String n = Nombre.getText();
        String t = Tipo.getText();
      
        
        eliminar();
        
        
        
            ID.setText("Ingresa el ID");
            ID.setForeground(Color.gray);
            
           
            Nombre.setText("Ingresa el nombre");
            Nombre.setForeground(Color.gray);
        
            Tipo.setText("Ingresa el tipo");
            Tipo.setForeground(Color.gray);
                  
           
        
    }//GEN-LAST:event_jPanel1MouseClicked
//Quitar esto
    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
       jPanel1.setBackground(new Color(41, 112, 202));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
                jPanel1.setBackground(new Color(47,45,46));

    }//GEN-LAST:event_jPanel1MouseExited
 float suma = 0 ;
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
  
   
    
    String Producto = jComboBox1.getSelectedItem().toString();
    
       int spin2 = (int) jSpinner1.getValue();
       
       for(int i=0;i<produc.size();i++){
       
       if(produc.get(i).Nombre==Producto){
       Carrito cr = new Carrito(produc.get(i).ID,produc.get(i).Nombre,produc.get(i).Tipo,produc.get(i).Precio,spin2);
        suma+=spin2*produc.get(i).Precio;
        carrito.add(cr);
       }
       
       }
       
        
         eliminar();
        addRowToJTable();
        jLabel4.setText("$ "+suma);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
         jPanel2.setBackground(new Color(41, 112, 202));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
           jPanel2.setBackground(new Color(47,45,46));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
         
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    
    
    
    
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JTextField Tipo;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
    
}
